import type { Metadata } from 'next';
import { Anton, Outfit } from 'next/font/google';

import './globals.css';

const anton = Anton({
  weight: '400',
  // variable: '--font-geist-mono',
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
const outfit = Outfit({
  weight: '500',
  // variable: '--font-geist-mono',
  variable: '--font-medium',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Would do you like get out with me?',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${outfit.variable} antialiased`}>{children}</body>
    </html>
  );
}
